server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
  type-aliases-package: entity                        # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml  # mapper映射文件

spring:
  profiles: dev
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01        # 数据库url
    username: root
    password: 1234
    dbcp2:
      min-idle: 5                                     # 数据库连接池的最小维持数
      initial-size: 5                                 # 初始化连接数
      max-total: 5                                    # 最大连接数
      max-wait-millis: 200                            # 最大等待毫秒数

eureka:
  client:  # eureka client注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost1:7001/eureka   #  ,http://localhost2:7002/eureka,http://localhost3:7003/eureka
  instance:
    instance-id: microservicecloud-dept8001-hystrix   # 给自己在eureka注册中心起别名
    prefer-ip-address: true                   # 显示完整ip

info:
  app.name: cliffford-microservicecloud
  company.name: cliff.ford
  build.artifactId: $project.artfactId$
  build.version: ${project.version}$

management:
  endpoints:
    web:
      exposure:
        include: ["hystrix.stream"]
---
server:
  port: 8002

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  # mybatis配置文件所在路径
  type-aliases-package: entity                        # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml  # mapper映射文件

spring:
  profiles: test
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB02        # 数据库url
    username: root
    password: 1234
    dbcp2:
      min-idle: 5                                     # 数据库连接池的最小维持数
      initial-size: 5                                 # 初始化连接数
      max-total: 5                                    # 最大连接数
      max-wait-millis: 200                            # 最大等待毫秒数

eureka:
  client:  # eureka client注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost2:7002/eureka   #  ,http://localhost2:7002/eureka,http://localhost3:7003/eureka
  instance:
    instance-id: microservicecloud-dept8002-hystrix   # 给自己在eureka注册中心起别名
    prefer-ip-address: true                   # 显示完整ip

info:
  app.name: cliffford-microservicecloud
  company.name: cliff.ford
  build.artifactId: $project.artfactId$
  build.version: ${project.version}$

management:
  endpoints:
    web:
      exposure:
        include: ["hystrix.stream"]